version: "3.9"
services:
  monitorix:
    build: ./monitorix
    image: monitorix:local
    hostname: monitorix-apu2e4
    container_name: monitorix
    privileged: true
    environment:
      - TZ=${TZ:-Europe/Rome}
    volumes:
      - ./monitorix.conf:/etc/monitorix/monitorix.conf
      - monitorix_data:/var/lib/monitorix
      - ./ssmtp.conf:/etc/ssmtp/ssmtp.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
   monitorix_data:
