version: "3.9"
services:
  tasmoadmin:
    image: ghcr.io/tasmoadmin/tasmoadmin:latest
    hostname: tasmoadmin
    container_name: tasmoadmin
    privileged: true
    volumes:
      - ./data:/data
    ports:
      - 80:80
    restart: unless-stopped
    mac_address: de:ad:be:ef:06:04
    networks:
      mgmt_vlan:
        ipv4_address: 172.16.6.4
networks:
  mgmt_vlan:
    name: mgmt_vlan
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      config:
        - subnet: 172.16.6.0/24
          gateway: 172.16.6.1
