version: "3.8"
services:
  rss2email:
    command: /app/rss2email daemon -verbose ${TO_EMAIL}
    env_file:
      - .env
    restart: unless-stopped
    image: tuxmealux/rss2email:latest
    volumes:
    - ./config:/root/.rss2email
    dns:
      - 172.16.10.1
    mac_address: de:ad:be:ef:10:03
    networks:
      untrusted_vlan:
        ipv4_address: 172.16.10.3
networks:
  untrusted_vlan:
    driver: macvlan
    driver_opts:
      parent: enp1s0.10
    ipam:
      config:
        - subnet: 172.16.10.0/24
          gateway: 172.16.10.1

